import pg from "pg";
// title: src/core/services/db.ts
import { CamelCasePlugin, Kysely, PostgresDialect } from "kysely";

import env from "#start/env";
import type { DB } from "#types/db";

const dialect = new PostgresDialect({
  pool: new pg.Pool({
    host: env.get("POSTGRES_HOST"),
    port: env.get("POSTGRES_PORT"),
    database: env.get("POSTGRES_DB"),
    user: env.get("POSTGRES_USER"),
    password: env.get("POSTGRES_PASSWORD"),
  }),
});

export const db = new Kysely<DB>({
  dialect,
  // The schema uses snake_case columns while the app speaks camelCase; this
  // plugin translates identifiers in both directions at runtime, matching the
  // camelCase types generated by `kysely-codegen --camel-case`.
  plugins: [new CamelCasePlugin()],
});
