/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthAccessTokens {
  abilities: string;
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  hash: string;
  id: string;
  lastUsedAt: Timestamp | null;
  name: string | null;
  tokenableId: string;
  type: string;
  updatedAt: Timestamp;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  fullName: string | null;
  id: string;
  password: string;
  role: Generated<number>;
  updatedAt: Timestamp;
}

export interface DB {
  authAccessTokens: AuthAccessTokens;
  users: Users;
}
